# CMake generated Testfile for 
# Source directory: /home/dev001/LEDGIS/unittests
# Build directory: /home/dev001/LEDGIS/build/unittests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(abi_unit_test_wabt "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=abi_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--wabt")
add_test(abi_unit_test_eos-vm-oc "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=abi_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--eos-vm-oc")
add_test(abi_unit_test_eos-vm "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=abi_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--eos-vm")
add_test(abi_unit_test_eos-vm-jit "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=abi_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--eos-vm-jit")
add_test(api_unit_test_wabt "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=api_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--wabt")
set_tests_properties(api_unit_test_wabt PROPERTIES  COST "5000")
add_test(api_unit_test_eos-vm-oc "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=api_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--eos-vm-oc")
set_tests_properties(api_unit_test_eos-vm-oc PROPERTIES  COST "5000")
add_test(api_unit_test_eos-vm "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=api_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--eos-vm")
set_tests_properties(api_unit_test_eos-vm PROPERTIES  COST "5000")
add_test(api_unit_test_eos-vm-jit "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=api_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--eos-vm-jit")
set_tests_properties(api_unit_test_eos-vm-jit PROPERTIES  COST "5000")
add_test(auth_unit_test_wabt "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=auth_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--wabt")
add_test(auth_unit_test_eos-vm-oc "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=auth_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--eos-vm-oc")
add_test(auth_unit_test_eos-vm "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=auth_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--eos-vm")
add_test(auth_unit_test_eos-vm-jit "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=auth_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--eos-vm-jit")
add_test(block_unit_test_wabt "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=block_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--wabt")
add_test(block_unit_test_eos-vm-oc "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=block_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--eos-vm-oc")
add_test(block_unit_test_eos-vm "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=block_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--eos-vm")
add_test(block_unit_test_eos-vm-jit "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=block_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--eos-vm-jit")
add_test(block_timestamp_unit_test_wabt "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=block_timestamp_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--wabt")
add_test(block_timestamp_unit_test_eos-vm-oc "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=block_timestamp_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--eos-vm-oc")
add_test(block_timestamp_unit_test_eos-vm "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=block_timestamp_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--eos-vm")
add_test(block_timestamp_unit_test_eos-vm-jit "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=block_timestamp_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--eos-vm-jit")
add_test(bootseq_unit_test_wabt "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=bootseq_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--wabt")
add_test(bootseq_unit_test_eos-vm-oc "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=bootseq_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--eos-vm-oc")
add_test(bootseq_unit_test_eos-vm "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=bootseq_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--eos-vm")
add_test(bootseq_unit_test_eos-vm-jit "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=bootseq_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--eos-vm-jit")
add_test(currency_unit_test_wabt "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=currency_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--wabt")
add_test(currency_unit_test_eos-vm-oc "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=currency_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--eos-vm-oc")
add_test(currency_unit_test_eos-vm "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=currency_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--eos-vm")
add_test(currency_unit_test_eos-vm-jit "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=currency_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--eos-vm-jit")
add_test(database_unit_test_wabt "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=database_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--wabt")
add_test(database_unit_test_eos-vm-oc "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=database_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--eos-vm-oc")
add_test(database_unit_test_eos-vm "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=database_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--eos-vm")
add_test(database_unit_test_eos-vm-jit "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=database_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--eos-vm-jit")
add_test(delay_unit_test_wabt "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=delay_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--wabt")
set_tests_properties(delay_unit_test_wabt PROPERTIES  COST "3000")
add_test(delay_unit_test_eos-vm-oc "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=delay_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--eos-vm-oc")
set_tests_properties(delay_unit_test_eos-vm-oc PROPERTIES  COST "3000")
add_test(delay_unit_test_eos-vm "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=delay_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--eos-vm")
set_tests_properties(delay_unit_test_eos-vm PROPERTIES  COST "3000")
add_test(delay_unit_test_eos-vm-jit "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=delay_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--eos-vm-jit")
set_tests_properties(delay_unit_test_eos-vm-jit PROPERTIES  COST "3000")
add_test(led_token_unit_test_wabt "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=led_token_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--wabt")
add_test(led_token_unit_test_eos-vm-oc "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=led_token_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--eos-vm-oc")
add_test(led_token_unit_test_eos-vm "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=led_token_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--eos-vm")
add_test(led_token_unit_test_eos-vm-jit "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=led_token_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--eos-vm-jit")
add_test(forked_unit_test_wabt "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=forked_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--wabt")
add_test(forked_unit_test_eos-vm-oc "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=forked_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--eos-vm-oc")
add_test(forked_unit_test_eos-vm "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=forked_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--eos-vm")
add_test(forked_unit_test_eos-vm-jit "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=forked_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--eos-vm-jit")
add_test(misc_unit_test_wabt "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=misc_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--wabt")
add_test(misc_unit_test_eos-vm-oc "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=misc_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--eos-vm-oc")
add_test(misc_unit_test_eos-vm "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=misc_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--eos-vm")
add_test(misc_unit_test_eos-vm-jit "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=misc_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--eos-vm-jit")
add_test(payloadless_unit_test_wabt "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=payloadless_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--wabt")
add_test(payloadless_unit_test_eos-vm-oc "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=payloadless_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--eos-vm-oc")
add_test(payloadless_unit_test_eos-vm "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=payloadless_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--eos-vm")
add_test(payloadless_unit_test_eos-vm-jit "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=payloadless_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--eos-vm-jit")
add_test(producer_schedule_unit_test_wabt "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=producer_schedule_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--wabt")
add_test(producer_schedule_unit_test_eos-vm-oc "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=producer_schedule_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--eos-vm-oc")
add_test(producer_schedule_unit_test_eos-vm "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=producer_schedule_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--eos-vm")
add_test(producer_schedule_unit_test_eos-vm-jit "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=producer_schedule_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--eos-vm-jit")
add_test(protocol_feature_unit_test_wabt "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=protocol_feature_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--wabt")
add_test(protocol_feature_unit_test_eos-vm-oc "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=protocol_feature_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--eos-vm-oc")
add_test(protocol_feature_unit_test_eos-vm "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=protocol_feature_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--eos-vm")
add_test(protocol_feature_unit_test_eos-vm-jit "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=protocol_feature_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--eos-vm-jit")
add_test(ram_unit_test_wabt "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=ram_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--wabt")
add_test(ram_unit_test_eos-vm-oc "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=ram_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--eos-vm-oc")
add_test(ram_unit_test_eos-vm "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=ram_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--eos-vm")
add_test(ram_unit_test_eos-vm-jit "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=ram_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--eos-vm-jit")
add_test(resource_limits_unit_test_wabt "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=resource_limits_test" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--wabt")
add_test(resource_limits_unit_test_eos-vm-oc "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=resource_limits_test" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--eos-vm-oc")
add_test(resource_limits_unit_test_eos-vm "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=resource_limits_test" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--eos-vm")
add_test(resource_limits_unit_test_eos-vm-jit "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=resource_limits_test" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--eos-vm-jit")
add_test(restart_chain_unit_test_wabt "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=restart_chain_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--wabt")
add_test(restart_chain_unit_test_eos-vm-oc "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=restart_chain_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--eos-vm-oc")
add_test(restart_chain_unit_test_eos-vm "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=restart_chain_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--eos-vm")
add_test(restart_chain_unit_test_eos-vm-jit "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=restart_chain_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--eos-vm-jit")
add_test(snapshot_unit_test_wabt "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=snapshot_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--wabt")
add_test(snapshot_unit_test_eos-vm-oc "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=snapshot_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--eos-vm-oc")
add_test(snapshot_unit_test_eos-vm "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=snapshot_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--eos-vm")
add_test(snapshot_unit_test_eos-vm-jit "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=snapshot_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--eos-vm-jit")
add_test(special_account_unit_test_wabt "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=special_account_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--wabt")
add_test(special_account_unit_test_eos-vm-oc "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=special_account_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--eos-vm-oc")
add_test(special_account_unit_test_eos-vm "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=special_account_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--eos-vm")
add_test(special_account_unit_test_eos-vm-jit "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=special_account_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--eos-vm-jit")
add_test(unapplied_transaction_queue_unit_test_wabt "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=unapplied_transaction_queue_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--wabt")
add_test(unapplied_transaction_queue_unit_test_eos-vm-oc "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=unapplied_transaction_queue_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--eos-vm-oc")
add_test(unapplied_transaction_queue_unit_test_eos-vm "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=unapplied_transaction_queue_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--eos-vm")
add_test(unapplied_transaction_queue_unit_test_eos-vm-jit "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=unapplied_transaction_queue_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--eos-vm-jit")
add_test(wasm_unit_test_wabt "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=wasm_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--wabt")
set_tests_properties(wasm_unit_test_wabt PROPERTIES  COST "4000")
add_test(wasm_unit_test_eos-vm-oc "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=wasm_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--eos-vm-oc")
set_tests_properties(wasm_unit_test_eos-vm-oc PROPERTIES  COST "4000")
add_test(wasm_unit_test_eos-vm "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=wasm_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--eos-vm")
set_tests_properties(wasm_unit_test_eos-vm PROPERTIES  COST "4000")
add_test(wasm_unit_test_eos-vm-jit "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=wasm_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--eos-vm-jit")
set_tests_properties(wasm_unit_test_eos-vm-jit PROPERTIES  COST "4000")
add_test(whitelist_blacklist_unit_test_wabt "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=whitelist_blacklist_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--wabt")
add_test(whitelist_blacklist_unit_test_eos-vm-oc "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=whitelist_blacklist_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--eos-vm-oc")
add_test(whitelist_blacklist_unit_test_eos-vm "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=whitelist_blacklist_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--eos-vm")
add_test(whitelist_blacklist_unit_test_eos-vm-jit "/home/dev001/LEDGIS/build/unittests/unit_test" "--run_test=whitelist_blacklist_tests" "--report_level=detailed" "--color_output" "--catch_system_errors=no" "--" "--eos-vm-jit")
subdirs("test-contracts")
subdirs("contracts")
subdirs("snapshots")
